/**
 * `@qywork/core` 的对外接口。**此处列出的即对外承诺，未列出的均为内部实现。**
 * 使用具名导出，不用 `export *`（B6）；新增导出前先确认它确有包外调用方（B3）。
 *
 * 事件与指令的成员类型有意不逐个导出。`AgentEvent` / `ClientCommand` 是可辨识
 * 联合，消费方按 `type` 收窄即可得到成员类型；逐个导出会把三十多个只在联合中
 * 出现的名称暴露出去，而它们没有调用点。
 *
 * 不要为 `domain/` 和 `protocol/` 各建一个 `index.ts`：它们只会被本文件引用，
 * 相当于同一份清单维护两次。
 */

// Art 页面：尺寸参数与 viewport 读写。服务端生成、尺寸读取与界面渲染共用
export {
  ART_DEFAULT_SIZE,
  ART_MENTION,
  ART_SIZE_PARAM,
  artSizeOf,
  artViewportOf,
  insertAfterHead,
  withArtViewport,
} from './domain/art.ts'
// 画布文档：格式、操作与不变式。服务端画布服务、画布工具与界面共用同一套规则
export {
  addVersions,
  applyCanvasOps,
  blankBox,
  CANVAS_FILE_KINDS,
  CANVAS_SCHEMA_VERSION,
  type CanvasClip,
  type CanvasDoc,
  type CanvasEdge,
  type CanvasFileKind,
  type CanvasFileNode,
  type CanvasGenerateNode,
  type CanvasMade,
  type CanvasMode,
  type CanvasNode,
  type CanvasNodeState,
  type CanvasOp,
  type CanvasPixels,
  type CanvasResult,
  type CanvasRunRecord,
  type CanvasRunResult,
  type CanvasTimelineNode,
  type CanvasVersion,
  type CanvasView,
  canvasFileKind,
  canvasMediaOf,
  compilePrompt,
  copyOps,
  displayNameOf,
  emptyCanvas,
  fitBox,
  inputsOf,
  type MentionStyle,
  mentionsOf,
  modeOf,
  newCanvasId,
  parseCanvas,
  parseCanvasOps,
  recordRun,
  serializeCanvas,
  settleVersion,
  TIMELINE_W,
  validateCanvas,
} from './domain/canvas.ts'
// id 与构造器：账本、事件、协议三处都按它们对齐类型
export {
  type ConversationId,
  type GoalId,
  type MessageId,
  newConversationId,
  newGoalId,
  newMessageId,
  newProviderRequestId,
  newResourceId,
  newRunId,
  newStepId,
  newUsageId,
  newWorkspaceId,
  type ProviderRequestId,
  type ResourceId,
  type RunId,
  type StepId,
  type WorkspaceId,
} from './domain/ids.ts'
// 生成模型的协议与类别：配置校验、目录、设置页共用
export {
  defaultMediaKind,
  GENERATE_OUTPUTS,
  type GenerateOutput,
  isArkEndpoint,
  isDashScopeEndpoint,
  MEDIA_INPUT_ROLES,
  MEDIA_KIND_OUTPUT,
  MEDIA_KINDS,
  MEDIA_OUTPUT_UNIT,
  MEDIA_OUTPUTS,
  type MediaInputRole,
  type MediaKind,
  type MediaOutput,
  type MediaSpend,
} from './domain/media.ts'
export {
  activeMediaParams,
  type MediaParamDefinition,
  type MediaParamValue,
  mediaOperationFor,
  mediaParamProblem,
  mediaParamValues,
  resolveMediaParam,
} from './domain/media-params.ts'
// 领域模型：落库结构与读数规则，几乎每个包都依赖
export {
  type Attachment,
  attachmentTypeOf,
  baseNameOf,
  CACHE_ROUTINGS,
  type CacheRouting,
  CONTEXT_GROUPS,
  type CompactionCut,
  type CompactionFacts,
  type CompactionManifest,
  type ContextBreakdown,
  type ContextGroup,
  type ContextOmitted,
  type Conversation,
  type Currency,
  deriveConversationTitle,
  EFFORT_ORDER,
  type EffortLevel,
  emptyBreakdown,
  emptyOmitted,
  envelopeHeadTokens,
  type FileChange,
  type FileReadProgress,
  type FoldedFileChange,
  type FollowUp,
  foldFileChanges,
  formatCosts,
  formatMoney,
  type Goal,
  type GoalAction,
  type GoalStatus,
  type GoalWriteResult,
  type IntermediateResourceRef,
  isInlineAudio,
  isInlineImage,
  isInlineVideo,
  isNoticeStep,
  type Message,
  matchesToolCallCheck,
  mimeOf,
  type NodePhase,
  type NodeState,
  type PermissionMode,
  PROVIDER_KINDS,
  type ProviderFailureCause,
  type ProviderKind,
  type ProviderRequest,
  type ProviderRequestConfiguration,
  type ProviderRequestContentKind,
  type ProviderRequestDiagnostic,
  type ProviderRequestPurpose,
  type ProviderRequestStatus,
  type ProviderRetryDecision,
  type ProviderTransportReading,
  REASONING_ECHOES,
  type ReasoningEcho,
  type ResourceCoverage,
  type ResourceStatus,
  type ResponseReasoning,
  type Run,
  type RunContextSegment,
  type RunInterruption,
  type RunStatus,
  type RunUsage,
  reconcileBreakdown,
  runCosts,
  type Step,
  type StepKind,
  type StepPayload,
  type StopReason,
  THINKING_MODES,
  type ThinkingMode,
  TOOL_SCHEMA_MODES,
  type TodoItem,
  type ToolActionStatus,
  type ToolCallCheck,
  type ToolOutcomeWire,
  type ToolSchemaMode,
  todoProgress,
  toPosixPath,
  type UsageBucket,
  type UsageKind,
  type UsageLedgerRow,
  type UsageTotals,
  type Workspace,
} from './domain/model.ts'

// 定时任务：仓储（store）、HTTP 接口、模型工具与面板共用同一份类型与时间判定
export {
  diagnoseSchedule,
  isDue,
  nextRunAt,
  type Schedule,
  type ScheduleDraft,
  type ScheduleKind,
  type ScheduleLastRun,
  type ScheduleView,
} from './domain/schedule.ts'

// workflow 的跨层序列化契约与纯投影：team/server/web 共用，不能各自计算。
export {
  applyRevision,
  checkpointOutput,
  DEFAULT_MAX_CONCURRENT,
  foldWorkflow,
  nodeSettled,
  parseSubagentTarget,
  parseWorkflowCall,
  type RevisionClosureResult,
  readyCheckpoint,
  revisionClosure,
  SUBAGENT_KIND_LABEL,
  type SubagentKind,
  type SubagentSpec,
  type SubagentTarget,
  type SubagentTargetParse,
  targetLabel,
  type WorkflowAgentNode,
  type WorkflowAppliedReview,
  type WorkflowCall,
  type WorkflowCallRecord,
  type WorkflowCheckpointNode,
  type WorkflowFoldResult,
  type WorkflowNode,
  type WorkflowParseResult,
  type WorkflowPhase,
  type WorkflowProjection,
  type WorkflowReceipt,
  type WorkflowRevision,
  type WorkflowTransition,
  workflowGroupId,
  workflowResults,
  workflowTransitionOf,
} from './domain/workflow.ts'
// 运行日志：各包只调用 `log.*`，输出位置由 `setLogSink` 注入的 sink 决定
export {
  formatLogLine,
  type LogLevel,
  type LogRecord,
  type LogSink,
  log,
  setLogSink,
} from './log.ts'
// 服务端 → 客户端的事件
export type {
  ActionDescriptor,
  ActionKind,
  AgentEvent,
  BrowserStateEvent,
  DesktopStateEvent,
  DesktopTargetEvent,
  ErrorCode,
  EventEnvelope,
  GitStateEvent,
} from './protocol/events.ts'
// 单次派发任务卡上子节点的 id：服务端发送事件、前端绘制节点，两侧必须使用同一个值
export { SUBAGENT_NODE_ID } from './protocol/events.ts'
export type {
  ConversationChangeStep,
  ConversationChangesPageResponse,
  ConversationChangeTurn,
  ConversationHistoryPage,
  ConversationHistoryPageResponse,
  ConversationLiveSnapshot,
  ConversationRunsResponse,
  ConversationUsageResponse,
  LiveRequestSnapshot,
  UsageResponse,
} from './protocol/http.ts'
// 原生浏览器宿主连接的帧与操作枚举：Rust 宿主与 server 两侧按同一份定义编解码
export {
  BROWSER_EVENT_KINDS,
  type BrowserEventFrame,
  type BrowserEventKind,
  type BrowserOp,
  type BrowserRequestFrame,
  type BrowserResultFrame,
  type BrowserTabSnapshot,
  type DownloadBlockReason,
  type HostReadyFrame,
  NATIVE_BROWSER_PATH,
  type NativeBrowserUpFrame,
} from './protocol/native-browser.ts'
// 桌面原生宿主连接的帧与操作枚举：宿主与 server 两侧按同一份定义编解码
export {
  type DesktopAction,
  type DesktopActionKind,
  type DesktopBlockingWindow,
  type DesktopCompleteness,
  type DesktopDelivery,
  type DesktopDispatch,
  type DesktopDragTarget,
  type DesktopEventFrame,
  type DesktopGrant,
  type DesktopHostReadyFrame,
  type DesktopImageBody,
  type DesktopImageGeometry,
  type DesktopImageSource,
  type DesktopModifier,
  type DesktopMouseButton,
  type DesktopNode,
  type DesktopNodeAction,
  type DesktopObservation,
  type DesktopOp,
  type DesktopRangeState,
  type DesktopRect,
  type DesktopRequestFrame,
  type DesktopResultFrame,
  type DesktopScrollDirection,
  type DesktopScrollState,
  type DesktopScrollStep,
  type DesktopSelectionState,
  type DesktopTarget,
  type DesktopTextBody,
  type DesktopTextSelection,
  type DesktopToggleState,
  type DesktopTreeBody,
  type DesktopWaitUntil,
  type DesktopWindow,
  type DesktopWindowState,
  imagePointToScreen,
  imageRectToScreen,
  NATIVE_DESKTOP_PATH,
  type NativeDesktopUpFrame,
  screenPointToImage,
} from './protocol/native-desktop.ts'
// 两条宿主连接共用的凭据头
export { NATIVE_HOST_KEY_HEADER } from './protocol/native-host.ts'
// 客户端 → 服务端的指令、握手与配对
export {
  type BrowserCapability,
  type ClientCommand,
  type ClientOrigin,
  type CommandRejectedFrame,
  type CommandRejectReason,
  type DesktopCapability,
  decodePairingUrl,
  type EnvDependency,
  encodePairingUrl,
  type HelloErrFrame,
  type HelloFrame,
  type HelloOkFrame,
  type PairingPayload,
  type ResumePosition,
  ROLE_COMMAND,
  type ServerCapabilities,
} from './protocol/transport.ts'
export type { UpdateAction, UpdatePreferences, UpdateSnapshot } from './protocol/updates.ts'
