"""read 的结构提取与三种格式的机械检查。

结构提取供模型阅读：段落、表格、形状、单元格等的位置与内容，输出紧凑文本。
机械检查只报告能从文件本身证明的事实；遮挡与溢出等需要查看页面才能判断的问题，只给出「疑似」级别。
"""

import re
import zipfile

from lxml import etree

from com import XL_ERROR_NAMES

W = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"
WP = "http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing"
EMU_PER_CM = 360000
EMU_PER_TWIP = 635

XL_ERROR_TEXTS = set(XL_ERROR_NAMES.values())
VOLATILE = re.compile(r"\b(NOW|TODAY|RAND|RANDBETWEEN|OFFSET|INDIRECT)\s*\(", re.I)


def _cm(emu):
    return None if emu is None else round(emu / EMU_PER_CM, 2)


def _clip(text, n=200):
    text = " ".join((text or "").split())
    return text if len(text) <= n else text[:n] + "…"


def _parse_range(rng):
    if not rng:
        return None
    # 段落号可带 read 输出中的 P 前缀（P62-P72）。
    m = re.fullmatch(r"\s*[Pp]?(\d+)\s*(?:-\s*[Pp]?(\d+))?\s*", str(rng))
    if not m:
        return None
    a = int(m.group(1))
    return (a, int(m.group(2)) if m.group(2) else a)


# 文档库写入文档属性的默认值：python-docx 的作者与备注、python-pptx 的最后修改者与备注、openpyxl 的创建者。
LIBRARY_DEFAULTS = {"python-docx", "python-pptx", "openpyxl", "Steve Canny"}
LIBRARY_NOTES = ("generated by python-docx", "generated using python-pptx")


def check_metadata(path):
    """文档属性仍为生成库的默认值时报告：这些值会显示在文件属性与办公软件的信息面板中。"""
    dc, cp = "http://purl.org/dc/elements/1.1/", \
        "http://schemas.openxmlformats.org/package/2006/metadata/core-properties"
    try:
        with zipfile.ZipFile(path) as z:
            core = etree.fromstring(z.read("docProps/core.xml"))
    except (KeyError, zipfile.BadZipFile, etree.XMLSyntaxError):
        return []
    found = []
    for tag, label in ((f"{{{dc}}}creator", "作者"), (f"{{{cp}}}lastModifiedBy", "最后修改者"),
                       (f"{{{dc}}}description", "备注")):
        el = core.find(tag)
        value = (el.text or "").strip() if el is not None else ""
        if value in LIBRARY_DEFAULTS or value.startswith(LIBRARY_NOTES):
            found.append(f"{label}「{value}」")
    if not found:
        return []
    return [{"level": "warning", "code": "library_metadata",
             "message": f"文档属性是生成库的默认值：{'、'.join(found)}；改为真实作者或清空"}]


SHOWN_PER_CODE = 5


def _condense(checks):
    """同一类检查超过 SHOWN_PER_CODE 条时只保留前几条，并追加一条总数，避免结果被同类提示占满。"""
    out, seen, total = [], {}, {}
    for c in checks:
        total[c["code"]] = total.get(c["code"], 0) + 1
    for c in checks:
        n = seen[c["code"]] = seen.get(c["code"], 0) + 1
        if n <= SHOWN_PER_CODE:
            out.append(c)
        elif n == SHOWN_PER_CODE + 1:
            out.append({"level": c["level"], "code": c["code"],
                        "message": f"同类（{c['code']}）另有 {total[c['code']] - SHOWN_PER_CODE} 处未列出"})
    return out


def check(path, fmt):
    checks = {"docx": check_docx, "pptx": check_pptx, "xlsx": check_xlsx}[fmt](path)
    return _condense(checks + check_metadata(path))


def read(path, fmt, rng=None):
    text = {"docx": read_docx, "pptx": read_pptx, "xlsx": read_xlsx}[fmt](path, rng)
    checks = check(path, fmt)
    if checks:
        text += "\n\n检查：\n" + "\n".join(f"- [{c['level']}] {c['message']}" for c in checks)
    return text, checks


# ───────────────────────── docx ─────────────────────────

def _field_kinds(body):
    """按文档顺序扫描域，返回 [(域类型, 是否位于目录域结果之内, 首个 begin 元素)]。"""
    out = []
    stack = []
    for el in body.iter(f"{{{W}}}fldChar", f"{{{W}}}instrText", f"{{{W}}}fldSimple"):
        tag = etree.QName(el).localname
        if tag == "fldSimple":
            kind = (el.get(f"{{{W}}}instr") or "").split()[:1]
            out.append(((kind[0] if kind else "").upper(), any(f["kind"] == "TOC" for f in stack),
                        el))
            continue
        if tag == "instrText":
            if stack:
                stack[-1]["instr"] += el.text or ""
            continue
        t = el.get(f"{{{W}}}fldCharType")
        if t == "begin":
            stack.append({"instr": "", "kind": None, "el": el})
        elif t in ("separate", "end") and stack:
            top = stack[-1]
            if top["kind"] is None:
                words = top["instr"].split()
                top["kind"] = words[0].upper() if words else ""
                inside_toc = any(f["kind"] == "TOC" for f in stack[:-1])
                out.append((top["kind"], inside_toc, top["el"]))
            if t == "end":
                stack.pop()
    return out


def _toc_result_text(body, begin):
    """目录域 separate 与 end 之间的文字。"""
    started = False
    depth = 0
    parts = []
    for el in body.iter(f"{{{W}}}fldChar", f"{{{W}}}t", f"{{{W}}}tab"):
        if el is begin:
            started = True
            depth = 1
            in_result = False
            continue
        if not started:
            continue
        tag = etree.QName(el).localname
        if tag == "fldChar":
            t = el.get(f"{{{W}}}fldCharType")
            if t == "begin":
                depth += 1
            elif t == "separate" and depth == 1:
                in_result = True
            elif t == "end":
                depth -= 1
                if depth == 0:
                    break
        elif in_result:
            parts.append("\t" if tag == "tab" else (el.text or ""))
    return "".join(parts)


def check_docx(path):
    checks = []
    with zipfile.ZipFile(path) as z:
        names = z.namelist()
        doc = etree.fromstring(z.read("word/document.xml"))
        styles = etree.fromstring(z.read("word/styles.xml")) if "word/styles.xml" in names else None
        theme = etree.fromstring(z.read("word/theme/theme1.xml")) if "word/theme/theme1.xml" in names else None
        settings = etree.fromstring(z.read("word/settings.xml")) if "word/settings.xml" in names else None
    body = doc.find(f"{{{W}}}body")
    theme_ea = {}
    if theme is not None:
        a = "http://schemas.openxmlformats.org/drawingml/2006/main"
        for kind in ("major", "minor"):
            ea = theme.find(f".//{{{a}}}{kind}Font/{{{a}}}ea")
            theme_ea[f"{kind}EastAsia"] = ea.get("typeface") if ea is not None else ""

    def east_asia(rpr_parent):
        """显式的 eastAsia 字体，或指向主题且主题中的东亚字体不为空。"""
        if rpr_parent is None:
            return False
        f = rpr_parent.find(f".//{{{W}}}rFonts")
        if f is None:
            return False
        if f.get(f"{{{W}}}eastAsia"):
            return True
        return bool(theme_ea.get(f.get(f"{{{W}}}eastAsiaTheme") or "", ""))

    has_ea = False
    if styles is not None:
        has_ea = bool(east_asia(styles.find(f"{{{W}}}docDefaults")))
        for s in styles.findall(f"{{{W}}}style"):
            if s.get(f"{{{W}}}type") == "paragraph" and s.get(f"{{{W}}}default") == "1":
                has_ea = has_ea or bool(east_asia(s.find(f"{{{W}}}rPr")))
    if not has_ea:
        checks.append({"level": "warning", "code": "east_asia_font_missing",
                       "message": "文档默认样式未设置中文（东亚）字体，中文将使用打开该文件的软件的默认字体；"
                                  "用 rFonts 的 eastAsia 为正文与标题样式指定中文字体"})

    sect = body.find(f"{{{W}}}sectPr")
    text_width = None
    if sect is not None:
        pg, mar = sect.find(f"{{{W}}}pgSz"), sect.find(f"{{{W}}}pgMar")
        if pg is not None and mar is not None:
            text_width = (int(pg.get(f"{{{W}}}w")) - int(mar.get(f"{{{W}}}left", 0))
                          - int(mar.get(f"{{{W}}}right", 0))) * EMU_PER_TWIP
    if text_width:
        for holder in body.iter(f"{{{WP}}}inline", f"{{{WP}}}anchor"):
            ext = holder.find(f"{{{WP}}}extent")
            pr = holder.find(f"{{{WP}}}docPr")
            if ext is not None and int(ext.get("cx")) > text_width * 1.01:
                name = pr.get("name") if pr is not None else "图片"
                checks.append({"level": "warning", "code": "image_wider_than_text",
                               "message": f"{name} 宽 {_cm(int(ext.get('cx')))} cm，超出版心宽度 "
                                          f"{_cm(text_width)} cm"})

    kinds = _field_kinds(body)
    tocs = [k for k in kinds if k[0] == "TOC"]
    for _, _, begin in tocs:
        if etree.QName(begin).localname == "fldSimple":
            continue
        result = _toc_result_text(body, begin)
        if not re.search(r"\t\s*\d+", result):
            checks.append({"level": "warning", "code": "toc_not_updated",
                           "message": "目录域尚无页码；需要目录页码时，write 传入 update_toc=true"})
    uf = settings.find(f"{{{W}}}updateFields") if settings is not None else None
    if uf is not None and uf.get(f"{{{W}}}val", "true") not in ("false", "0", "off"):
        checks.append({"level": "warning", "code": "update_fields_on_open",
                       "message": "settings.xml 设置了打开时更新域（updateFields），Word 打开文件时会询问是否更新；"
                                  "目录页码由 update_toc 回填，应删除该设置"})
    refs = [k for k in kinds if k[0] in ("PAGEREF", "REF") and not k[1]]
    if refs:
        checks.append({"level": "info", "code": "page_refs_outside_toc",
                       "message": f"目录以外有 {len(refs)} 个引用页码或书签的域（PAGEREF / REF），"
                                  "本工具不回填它们的结果"})
    return checks


def read_docx(path, rng=None):
    from docx import Document
    from docx.table import Table
    from docx.text.paragraph import Paragraph

    doc = Document(str(path))
    body = doc.element.body
    lines = []
    for i, s in enumerate(doc.sections, 1):
        lines.append(
            f"[节{i}] 页面 {_cm(s.page_width)}×{_cm(s.page_height)} cm，边距 上{_cm(s.top_margin)} "
            f"下{_cm(s.bottom_margin)} 左{_cm(s.left_margin)} 右{_cm(s.right_margin)} cm")
        head = " / ".join(p.text for p in s.header.paragraphs if p.text.strip())
        foot = " / ".join(p.text for p in s.footer.paragraphs if p.text.strip())
        if head:
            lines.append(f"  页眉：{_clip(head)}")
        if foot:
            lines.append(f"  页脚：{_clip(foot)}")
    window = _parse_range(rng)
    pi = ti = 0
    for child in body.iterchildren():
        tag = etree.QName(child).localname
        if tag == "p":
            pi += 1
            if window and not (window[0] <= pi <= window[1]):
                continue
            p = Paragraph(child, doc._body)
            extra = []
            n_img = len(child.findall(f".//{{{WP}}}inline")) + len(child.findall(f".//{{{WP}}}anchor"))
            if n_img:
                extra.append(f"图片×{n_img}")
            instr = "".join(t.text or "" for t in child.iter(f"{{{W}}}instrText")).split()
            if instr:
                extra.append(f"域 {instr[0]}")
            text = _clip(p.text, 300)
            if not text and not extra:
                continue
            lines.append(f"[P{pi}] {p.style.name if p.style is not None else ''} | {text}"
                         + (f"  〔{'，'.join(extra)}〕" if extra else ""))
        elif tag == "tbl":
            ti += 1
            if window and not (window[0] <= pi <= window[1]):
                continue
            t = Table(child, doc._body)
            rows = t.rows
            preview = []
            for r in list(rows)[:3]:
                preview.append(" | ".join(_clip(c.text, 30) for c in r.cells))
            lines.append(f"[T{ti}] 表格 {len(rows)}×{len(t.columns)}（在 P{pi} 之后）：" + " ‖ ".join(preview))
    shapes = [f"{s._inline.docPr.get('name')} {_cm(s.width)}×{_cm(s.height)} cm"
              for s in doc.inline_shapes]
    kinds = {}
    for k, _, _ in _field_kinds(body):
        kinds[k] = kinds.get(k, 0) + 1
    cp = doc.core_properties
    head = [f"docx · {pi} 段 · {ti} 表 · {len(shapes)} 张嵌入图"
            + (f" · 域 {', '.join(f'{k}×{v}' for k, v in kinds.items())}" if kinds else ""),
            f"文档属性：作者={cp.author!r} 最后修改者={cp.last_modified_by!r} 标题={cp.title!r}"]
    if shapes:
        head.append("嵌入图：" + "；".join(shapes[:40]) + (" …" if len(shapes) > 40 else ""))
    return "\n".join(head + lines)


# ───────────────────────── pptx ─────────────────────────

def _shape_box(shp):
    if None in (shp.left, shp.top, shp.width, shp.height):
        return None
    return (shp.left, shp.top, shp.left + shp.width, shp.top + shp.height)


def _comments(slide):
    return any(rel.reltype.endswith("/comments") for rel in slide.part.rels.values())


A = "http://schemas.openxmlformats.org/drawingml/2006/main"
CJK = re.compile(r"[\u3000-\u30ff\u3400-\u9fff\uf900-\ufaff\uff00-\uffef]")
DEFAULT_FONT_SIZE = 1800  # a:rPr 的 sz，百分之一磅；没有设置时按 18 磅


def _theme_ea(prs):
    """主题次要字体（正文）的东亚字体；空串表示未设置，中文字体由打开文件的软件决定。"""
    try:
        theme = prs.slide_masters[0].part.part_related_by(
            "http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme")
        ea = etree.fromstring(theme.blob).find(f".//{{{A}}}minorFont/{{{A}}}ea")
    except (KeyError, IndexError, etree.XMLSyntaxError):
        return ""
    return ea.get("typeface", "") if ea is not None else ""


def _run_has_ea(r, p):
    for holder in (r.find(f"{{{A}}}rPr"), p.find(f"{{{A}}}pPr/{{{A}}}defRPr")):
        ea = holder.find(f"{{{A}}}ea") if holder is not None else None
        if ea is not None and ea.get("typeface") and not ea.get("typeface").startswith("+"):
            return True
    return False


def _text_size(tf, width):
    """按字符宽度估算文字排版后所占的宽与高（EMU）：中文按一个字号宽，其余字符按 0.55 个字号宽，行高取字号的 1.2 倍。"""
    total, widest = 0, 0
    for p in tf.paragraphs:
        size = DEFAULT_FONT_SIZE
        for r in p.runs:
            if r.font.size is not None:
                size = r.font.size.centipoints
                break
        em = size * 127  # 百分之一磅 → EMU
        line_w = sum(em if CJK.match(ch) else em * 0.55 for ch in p.text)
        lines = max(1, -(-int(line_w) // max(int(width), 1)))
        widest = max(widest, min(line_w, width))
        total += lines * em * 1.2
    return widest, total


def _first_size(tf):
    for p in tf.paragraphs:
        for r in p.runs:
            if r.font.size is not None:
                return r.font.size.centipoints
    return DEFAULT_FONT_SIZE


def _frame(shp):
    """文本框的 bodyPr 与去除内边距后的可用宽高。"""
    body = shp.text_frame._txBody.find(f"{{{A}}}bodyPr")
    get = (lambda k, d: int(body.get(k, d))) if body is not None else (lambda k, d: d)
    left, right, top, bottom = get("lIns", 91440), get("rIns", 91440), get("tIns", 45720), get("bIns", 45720)
    return body, left, top, shp.width - left - right, shp.height - top - bottom


def _overflow(shp):
    """文本框关闭自动调整且开启换行时，估算文字高度超出框高 20% 以上即判定为疑似溢出。"""
    body, _, _, width, height = _frame(shp)
    if body is None or body.get("wrap") == "none":
        return None
    if body.find(f"{{{A}}}normAutofit") is not None or body.find(f"{{{A}}}spAutofit") is not None:
        return None
    # 最后一行下方的行距是空白，不计入文字高度。
    need = _text_size(shp.text_frame, width)[1] - _first_size(shp.text_frame) * 127 * 0.2
    return need if height > 0 and need > height * 1.2 else None


def _text_extent(shp):
    """文字实际占据的区域：按估算的宽高、段落对齐与垂直锚点放入文本框。旋转的形状使用外框。

    遮挡按该区域判定，不要改为按外框判定：外框通常比文字大得多，排版正常的成品也会报告上百条。
    """
    box = _shape_box(shp)
    if box is None or shp.rotation:
        return box
    body, left, top, width, height = _frame(shp)
    if width <= 0 or height <= 0:
        return box
    unwrapped = body is not None and body.get("wrap") == "none"
    w, h = _text_size(shp.text_frame, 10 ** 12 if unwrapped else width)
    h -= _first_size(shp.text_frame) * 127 * 0.2
    align = str(shp.text_frame.paragraphs[0].alignment or "")
    anchor = body.get("anchor", "t") if body is not None else "t"
    x = shp.left + left + ((width - w) / 2 if "CENTER" in align else width - w if "RIGHT" in align else 0)
    y = shp.top + top + ((height - h) / 2 if anchor == "ctr" else height - h if anchor == "b" else 0)
    return (x, y, x + w, y + h)


def check_pptx(path):
    from pptx import Presentation

    prs = Presentation(str(path))
    sw, sh = prs.slide_width, prs.slide_height
    tol = 12700
    checks = []
    theme_ea = _theme_ea(prs)
    no_ea = []
    for i, slide in enumerate(prs.slides, 1):
        texts = []
        for shp in slide.shapes:
            if shp.has_text_frame and shp.text_frame.text.strip():
                need = _overflow(shp)
                if need:
                    checks.append({"level": "warning", "code": "text_overflow",
                                   "message": f"第 {i} 页「{shp.name}」的文字估计需要 {_cm(need)} cm 高，"
                                              f"文本框只有 {_cm(shp.height)} cm，疑似溢出，需查看页面确认"})
                if not theme_ea:
                    for p in shp.text_frame._txBody.iter(f"{{{A}}}p"):
                        if any(CJK.search(r.findtext(f"{{{A}}}t") or "") and not _run_has_ea(r, p)
                               for r in p.iter(f"{{{A}}}r")):
                            no_ea.append(f"第 {i} 页「{shp.name}」")
                            break
            box = _shape_box(shp)
            if box and (box[0] < -tol or box[1] < -tol or box[2] > sw + tol or box[3] > sh + tol):
                checks.append({"level": "warning", "code": "off_slide",
                               "message": f"第 {i} 页「{shp.name}」超出页面范围"})
            if shp.is_placeholder and shp.has_text_frame and not shp.text_frame.text.strip():
                checks.append({"level": "info", "code": "empty_placeholder",
                               "message": f"第 {i} 页占位符「{shp.name}」为空"})
            if box and shp.has_text_frame and shp.text_frame.text.strip():
                texts.append((shp.name, _text_extent(shp)))
        for a in range(len(texts)):
            for b in range(a + 1, len(texts)):
                (na, ba), (nb, bb) = texts[a], texts[b]
                w = min(ba[2], bb[2]) - max(ba[0], bb[0])
                h = min(ba[3], bb[3]) - max(ba[1], bb[1])
                if w <= 0 or h <= 0:
                    continue
                smaller = min((ba[2] - ba[0]) * (ba[3] - ba[1]), (bb[2] - bb[0]) * (bb[3] - bb[1]))
                if smaller and w * h / smaller > 0.1:
                    checks.append({"level": "warning", "code": "text_overlap",
                                   "message": f"第 {i} 页「{na}」与「{nb}」的文字区域重叠，疑似遮挡，需查看页面确认"})
        if slide.has_notes_slide and slide.notes_slide.notes_text_frame.text.strip():
            checks.append({"level": "info", "code": "notes_present",
                           "message": f"第 {i} 页有演讲者备注"})
        if _comments(slide):
            checks.append({"level": "info", "code": "comments_present",
                           "message": f"第 {i} 页有批注"})
    if no_ea:
        where = "、".join(no_ea[:5]) + (f" 等 {len(no_ea)} 处" if len(no_ea) > 5 else "")
        checks.append({"level": "warning", "code": "east_asia_font_missing",
                       "message": f"{where}的中文未设置东亚字体，主题中也未设置，中文将使用打开该文件的软件的默认字体；"
                                  "为文字设置 a:ea，或在主题的次要字体中设置东亚字体"})
    return checks


def read_pptx(path, rng=None):
    from pptx import Presentation

    prs = Presentation(str(path))
    window = _parse_range(rng)
    lines = [f"pptx · {len(prs.slides)} 页 · 页面 {_cm(prs.slide_width)}×{_cm(prs.slide_height)} cm"]
    for i, slide in enumerate(prs.slides, 1):
        if window and not (window[0] <= i <= window[1]):
            continue
        lines.append(f"[第{i}页] 版式「{slide.slide_layout.name}」")
        for shp in slide.shapes:
            kind = str(shp.shape_type).split(".")[-1].split(" ")[0] if shp.shape_type else "?"
            pos = ""
            if _shape_box(shp):
                pos = (f" @({_cm(shp.left)},{_cm(shp.top)}) {_cm(shp.width)}×{_cm(shp.height)} cm")
            extra = []
            if shp.is_placeholder:
                extra.append(f"占位符 {shp.placeholder_format.type}")
            if getattr(shp, "has_chart", False) and shp.has_chart:
                ch = shp.chart
                extra.append(f"图表 {ch.chart_type} · {sum(len(p.series) for p in ch.plots)} 个系列")
            if getattr(shp, "has_table", False) and shp.has_table:
                t = shp.table
                extra.append(f"表格 {len(t.rows)}×{len(t.columns)}")
            if kind == "GROUP":
                extra.append(f"组合 {len(shp.shapes)} 个")
            text = _clip(shp.text_frame.text, 200) if shp.has_text_frame else ""
            lines.append(f"  - #{shp.shape_id}「{shp.name}」{kind}{pos}"
                         + (f"〔{'，'.join(extra)}〕" if extra else "") + (f"：{text}" if text else ""))
        if slide.has_notes_slide and slide.notes_slide.notes_text_frame.text.strip():
            lines.append(f"  备注：{_clip(slide.notes_slide.notes_text_frame.text)}")
        if _comments(slide):
            lines.append("  有批注")
    return "\n".join(lines)


# ───────────────────────── xlsx ─────────────────────────

def _formula(v):
    """单元格中的公式文本；不是公式时返回 None。数组公式在 openpyxl 中是对象，显示为 {公式}（数组 区域）。"""
    if isinstance(v, str) and v.startswith("="):
        return v
    text = getattr(v, "text", None)
    if isinstance(text, str):
        ref = getattr(v, "ref", "")
        return f"{{{text}}}" + (f"（数组 {ref}）" if ref else "")
    return None


def _load_xlsx(path):
    from openpyxl import load_workbook

    return load_workbook(str(path), data_only=False), load_workbook(str(path), data_only=True)


def check_xlsx(path):
    wbf, wbv = _load_xlsx(path)
    errors, missing, volatile = {}, 0, 0
    samples = {}
    for ws in wbf.worksheets:
        vs = wbv[ws.title]
        for row in ws.iter_rows():
            for c in row:
                formula = _formula(c.value)
                if formula is None:
                    continue
                cached = vs[c.coordinate].value
                if cached is None:
                    missing += 1
                elif isinstance(cached, str) and cached in XL_ERROR_TEXTS:
                    errors[cached] = errors.get(cached, 0) + 1
                    samples.setdefault(cached, []).append(f"{ws.title}!{c.coordinate}")
                if VOLATILE.search(formula):
                    volatile += 1
    checks = []
    for kind, n in errors.items():
        refs = "、".join(samples[kind][:5]) + (" 等" if n > 5 else "")
        checks.append({"level": "error", "code": "cached_errors",
                       "message": f"{n} 个公式的计算结果是 {kind}：{refs}"})
    if missing:
        checks.append({"level": "info", "code": "missing_cache",
                       "message": f"{missing} 个公式没有缓存值（结果为空字符串的公式同样计入）"})
    if getattr(wbf, "_external_links", None):
        checks.append({"level": "warning", "code": "external_links",
                       "message": f"工作簿引用了 {len(wbf._external_links)} 个外部文件，重算时不更新外部链接"})
    if volatile:
        checks.append({"level": "info", "code": "volatile_functions",
                       "message": f"{volatile} 个公式使用了易变函数（NOW / TODAY / RAND / OFFSET / INDIRECT），"
                                  "每次打开结果都可能不同"})
    return checks


def read_xlsx(path, rng=None):
    wbf, wbv = _load_xlsx(path)
    names = list(wbf.defined_names.keys()) if hasattr(wbf.defined_names, "keys") else []
    lines = [f"xlsx · {len(wbf.worksheets)} 个工作表"
             + (f" · 命名区域 {', '.join(names[:20])}" if names else "")]
    selected = [ws for ws in wbf.worksheets if not rng or ws.title == rng]
    if rng and not selected:
        lines.append(f"没有名为「{rng}」的工作表；已有：{'、'.join(ws.title for ws in wbf.worksheets)}")
    row_limit = 500 if rng else 60
    for ws in wbf.worksheets:
        formulas = sum(1 for row in ws.iter_rows() for c in row
                       if _formula(c.value) is not None)
        merged = [str(m) for m in ws.merged_cells.ranges]
        lines.append(f"[{ws.title}] 范围 {ws.dimensions} · {ws.max_row} 行 × {ws.max_column} 列 · "
                     f"公式 {formulas} 个 · 图表 {len(getattr(ws, '_charts', []))} · "
                     f"图片 {len(getattr(ws, '_images', []))}"
                     + (f" · 冻结 {ws.freeze_panes}" if ws.freeze_panes else "")
                     + (f" · 合并 {', '.join(merged[:10])}" + (" …" if len(merged) > 10 else "")
                        if merged else ""))
        if ws not in selected:
            continue
        vs = wbv[ws.title]
        shown = 0
        for row in ws.iter_rows(max_row=min(ws.max_row, row_limit), max_col=min(ws.max_column, 30)):
            cells = []
            for c in row:
                if c.value is None:
                    continue
                formula = _formula(c.value)
                if formula is not None:
                    cells.append(f"{c.coordinate}={formula} → {vs[c.coordinate].value!r}")
                else:
                    cells.append(f"{c.coordinate}={_clip(str(c.value), 60)}")
            if cells:
                lines.append("  " + "；".join(cells))
                shown += 1
        if ws.max_row > row_limit:
            lines.append(f"  …只列出前 {row_limit} 行；range 填写工作表名可查看更多行")
    return "\n".join(lines)
